/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package atm.account.unit

import io.kotest.core.spec.style.FreeSpec


class AppTest : FreeSpec({
    "foo" {
        assert(true)
    }

})
