/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package atm.simulation.backend

import io.kotest.core.spec.style.FreeSpec
import io.mockk.mockk
import io.mockk.verify

class AppTest : FreeSpec({
    "foo" {
        assert(true)
    }

})
